# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160414_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userID',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
