# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 21:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='major',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(default=datetime.datetime(2016, 4, 20, 21, 5, 4, 155693, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
