# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20160422_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
    ]
