# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 02:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_profile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(default=datetime.datetime(2016, 4, 23, 2, 20, 12, 313720, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
