# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20160427_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status_in_cmu',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate Student'), ('graduate', 'Graduate Student'), ('professor', 'Professor'), ('staff', 'School Staff'), ('non_cmu', 'Not in CMU')], default='undergraduate', max_length=2),
        ),
    ]
