# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 02:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20160427_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_background',
            field=models.FileField(default=datetime.datetime(2016, 4, 28, 2, 18, 1, 9370, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(default=datetime.datetime(2016, 4, 28, 2, 18, 7, 374746, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='status_in_cmu',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate Student'), ('graduate', 'Graduate Student'), ('professor', 'Professor'), ('staff', 'School Staff'), ('non_cmu', 'Not in CMU')], default='undergraduate', max_length=100),
        ),
    ]
