# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0018_auto_20160427_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Friend_user2', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Friend_user1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Friends',
                'verbose_name': 'Friend',
            },
        ),
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('rejected', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FriendshipRequest_user1', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FriendshipRequest_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Friendship Requests',
                'verbose_name': 'Friendship Request',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(choices=[('Food', 'Food'), ('Study', 'Study'), ('Other', 'Other')], default='Food', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together=set([('from_user', 'to_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([('from_user', 'to_user')]),
        ),
    ]
