# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 12:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0019_auto_20160428_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='profile_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status_in_cmu',
            field=models.CharField(choices=[('Undergraduate Student', 'Undergraduate Student'), ('Graduate Student', 'Graduate Student'), ('Professor', 'Professor'), ('Staff', 'School Staff'), ('No in Cmu', 'Not in CMU')], default='Undergraduate Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
