# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20160428_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_background',
        ),
    ]
