# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_profile_profile_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_photo',
            field=models.FileField(default=datetime.datetime(2016, 4, 28, 15, 20, 35, 470624, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
