# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 15:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0022_event_event_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Connection_user2', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Connection_user1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connection',
                'verbose_name_plural': 'Connections',
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('rejected', models.BooleanField(default=False)),
                ('viewed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='HelpRequest_user1', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='HelpRequest_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Help Request',
                'verbose_name_plural': 'Help Requests',
            },
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='friend',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='to_user',
        ),
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendshiprequest',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_photo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='facebook_page',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status_in_cmu',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studying_fields',
        ),
        migrations.AddField(
            model_name='event',
            name='prediction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='symptoms',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='radius',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Medical Staff', 'Medical Staff'), ('Patient', 'Patient')], default='Patient', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
        migrations.AlterUniqueTogether(
            name='helprequest',
            unique_together=set([('from_user', 'to_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set([('from_user', 'to_user')]),
        ),
    ]
