# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0023_auto_20180210_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connections',
            field=models.ManyToManyField(related_name='profile_connections', to=settings.AUTH_USER_MODEL),
        ),
    ]
