# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_profile_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='prediction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='symptoms',
            field=models.CharField(default='', max_length=500),
        ),
    ]
