# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-10 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20180210_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.FileField(default='/static/images/bg-01.jpg', upload_to=''),
        ),
    ]
