from django.conf.urls import url
from .import views

app_name = "user"

urlpatterns = [
    url(r'^register/$', views.register, name = "register"),
    url(r'^login/$', views.login_user, name="login"),
    url(r'^profile/$', views.display_profile, name="profile"),
    url(r'^profile/edit/$', views.edit_profile, name="edit_profile"),
    url(r'^profile/create/$', views.create_profile, name="create_profile"),
    url(r'^profile/events/$', views.all_events, name= "all_events"),
    url(r'^profile/events/create/$', views.create_event, name="create_event"),
    url(r'^$', views.logout_user, name="logout"),
    url(r'^profile/events/detail/(?P<event_id>[0-9]+)/$', views.event_detail, 
        name="event_detail"),
    url(r'^profile/events/delete/(?P<event_id>[0-9]+)/$', views.delete_event, 
        name='delete_event'),
    url(r'^profile/events/edit/(?P<event_id>[0-9]+)/$', views.edit_event,
     name='edit_event'),  
    url(r'^profile/my_events/current/$', views.myevents_current, 
        name="myevents_current"),
    url(r'^profile/my_events/past/$', views.myevents_past,name="myevents_past"),
    url(r'^profile/my_events/future/$', views.myevents_future,
        name="myevents_future"),
    url(r'^profile/disease_control/$', views.aggregateUserData, 
        name="disease_control"),
    url(r'^all_events/current/$', views.allevents_current, 
        name="allevents_current"),
    url(r'^all_events/past/$', views.allevents_past, name="allevents_past"),
    url(r'^all_events/future/$', views.allevents_future, 
        name="allevents_future"),
    url(r'^all_events/detail/(?P<event_id>[0-9]+)/$', views.otherevent_detail, 
        name="otherevent_detail"),
    url(r'^friends/$', views.display_friends, name="display_friends"),
    url(r'^user/detail/(?P<user_id>[0-9]+)/$', views.user_detail, 
        name='user_detail'),
    url(r'^friends/search/$', views.friends_search, name="friends_search"),
    url(r'^friends/search/send_request/(?P<user_id>[0-9]+)/$', 
        views.send_request, name = 'send_request'),
    url(r'^friends/request/$', views.display_request, name='display_request'),
    url(r'^friends/request/detail/(?P<message_id>[0-9]+)/$', 
        views.request_detail, name='request_detail'),
    url(r'^friends/request/detail/sent/(?P<message_id>[0-9]+)/$', 
        views.request_detail_sent, name='request_detail_sent'),
    url(r'^friends/request/detail/accept/(?P<message_id>[0-9]+)/$', 
        views.accept_friendship, name='accept_friendship'),
    url(r'^friends/request/detail/reject/(?P<message_id>[0-9]+)/$', 
        views.reject_friendship, name='reject_friendship'),
    url(r'^friends/detail/delete/friend/(?P<user_id>[0-9]+)/$', 
        views.delete_friend, name='delete_friend'),
    url(r'^friends/events/$', views.friends_events, name="friends_events"),
    url(r'^friends/events/past/$', views.friends_events_past, 
        name="friends_events_past"),
    url(r'^friends/events/current/$', views.friends_events_current, 
        name="friends_events_current"),
    url(r'^friends/events/future/$', views.friends_events_future, 
        name="friends_events_future"),
]
